### ISSUE TITLE
Plater metadata download retries

### ISSUE THREAD

**Issue by EvanDietzMorris** [helxplatform/translator-devops#670]
Plater uses a script (download_metadata.sh) to download metadata files in an init container, but sometimes these wget downloads fail. We need a way to retry on failure, or at least have the deployment show a failure.

**Comment by EvanDietzMorris** [comment]
some more information: part of the issue is that the implementation of wget provided by the busybox container does not provide much customization of retry options 

a simple readiness probe that checks for 200 responses from these endpoints as part of the deployment process could be another way to implement this: 
/metadata
/sri_testing_data
/meta_knowledge_graph

**Comment by jdr0887** [comment]
Take a look at branch "https://github.com/helxplatform/translator-devops/tree/issue_670".  This should get you pretty close to what you want.

**Comment by EvanDietzMorris** [comment]
This looks to be working well, thanks Jason!
